Dev/build action (#11)
* improved env managment script

* updated python version in pyproject

* updated actions

* typo correction tab/space

* updated version

diff --git a/create_uvenv b/create_uvenv
--- a/create_uvenv
+++ b/create_uvenv
@@ -1,14 +1,36 @@
 #!/bin/bash
+set -euo pipefail
+# set -x
+
+DEF_NAME=pyntb-uv
+
+# PYTHON_VERSION="--python-preference=system"
+# PYTHON_VERSION="--python 3.11"
+# PYTHON_VERSION="--python 3.12"
+# PYTHON_VERSION="--python 3.13"
+PYTHON_VERSION="--python 3.14"
+
+# -----------------------------------------------------------------------------
 
 # -- dir for all envs
 ENV_DIR=${ENV_DIR:-$HOME/ENV}
 mkdir -p $ENV_DIR
 
+# -- check uv install, update if necessary
+if ! command -v uv &> /dev/null; then
+    echo "uv not found; installing ..."
+    curl -LsSf https://astral.sh/uv/install.sh | sh
+    source $HOME/.cargo/env
+else
+    # uv self update
+    echo "uv already installed ($(uv --version))"
+fi
+
 # -- current env with link
-VENV=${ENV_DIR}/pyntb-uv
-VLNK=.venv
+VENV=${ENV_DIR}/${DEF_NAME}
+VLNK=.uvenv
 ln -sf $VENV $VLNK
-uv venv $VENV --python 3.11
+uv venv $VENV ${PYTHON_VERSION} --clear
 source $VENV/bin/activate
 
 # -- upgrade pip
